###
### A complete description of a Prefect Deployment for flow 'increment'
###
name: s3
description: deployment using s3 storage
version: snapshot
# The work queue that will handle this deployment's runs
work_queue_name: kubernetes
tags: []
parameters:
  i: 1
schedule: null
infra_overrides:
  image: orion-registry:5000/flow:latest
  env:
    AWS_ACCESS_KEY_ID: minioadmin
    AWS_SECRET_ACCESS_KEY: minioadmin
infrastructure:
  type: kubernetes-job
  env: {}
  labels: {}
  name: null
  command: null
  image: prefecthq/prefect:2.4.0-python3.9
  namespace: default
  service_account_name: null
  image_pull_policy: null
  cluster_config: null
  job:
    apiVersion: batch/v1
    kind: Job
    metadata:
      labels: {}
    spec:
      template:
        spec:
          parallelism: 1
          completions: 1
          restartPolicy: Never
          containers:
          - name: prefect-job
            env: []
  customizations: []
  job_watch_timeout_seconds: 5
  pod_watch_timeout_seconds: 60
  stream_output: true
  block_type_slug: kubernetes-job
  _block_type_slug: kubernetes-job

###
### DO NOT EDIT BELOW THIS LINE
###
flow_name: increment
manifest_path: null
storage:
  bucket_path: minio-flows/increment
  aws_access_key_id: null
  aws_secret_access_key: null
  _is_anonymous: false
  _block_document_name: minio-flows-increment
  _block_document_id: 5fc00f71-94c7-45d4-82f0-fb9f28472a33
  block_type_slug: s3
  _block_type_slug: s3
path: null
entrypoint: flows/param_flow.py:increment
parameter_openapi_schema:
  title: Parameters
  type: object
  properties:
    i:
      title: i
      type: integer
  required:
  - i
  definitions: null
