apiVersion: v1
kind: ServiceAccount
metadata:
  name: prefect-flows
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: daskKubernetes-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: prefect-flows
  namespace: default
roleRef:
  kind: Role
  name: daskKubernetes
  apiGroup: rbac.authorization.k8s.io
